projects:
  BLOApi:
    schemaPath: blo-app/src/graphql/schema.json
    includes:
      - blo-app/src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: blo-app/src/graphql
extensions:
  amplify:
    version: 3
