projects:
  app_serverless-blo:
    schemaPath: app_serverless-blo/src/graphql/schema.json
    includes:
      - app_serverless-blo/src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: app_serverless-blo/src/graphql
extensions:
  amplify:
    version: 3
