projects:
  bloapi:
    schemaPath: >-
      ./blo-frontend/src/graphql/schema.json
    includes:
      - ./blo-frontend/src/graphql/**/*.js
    excludes:
      - .//blo-backend/aws/amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: ./blo-frontend/src/graphql/
extensions:
  amplify:
    version: 3
